/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TaskMinder;

import java.sql.Connection;
import util.ConnectionFactory;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // Pede e retorna uma conexão:
        Connection c = ConnectionFactory.getConnection();
    }
}
